# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brian DeCost
email: brian.decost@nist.gov

description: > # this means to ignore newlines until "baseurl:"
  I'm a computational materials scientist with particular interest in microstructural evolution and the development and application of machine learning and computer vision methods for materials science.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
avatar: briandecost.jpg
github_username: bdecost
orcid: 0000-0002-3459-5888


position: Materials Scientist
department: Material Measurement Laboratory
institution: National Institute of Standards and Technology

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

excerpt_separator: <!--more-->

whitelist:
  - jekyll-redirect-from

header_pages:
  - 01_blog.md
  - 02_research.md
  - 03_publications.md